name: Linters

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      # 1. Checks out your repository's code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Sets up the specified Python version from the matrix
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Installs dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Runs the linter
      - name: Lint with Ruff
        run: |
          ruff check .

      # 5. Checks formatting (fails if code is not formatted)
      - name: Check formatting with Ruff
        run: |
          ruff format --check .

      # 6. Runs the tests
      - name: Run tests with Pytest
        run: |
          pytest
